AutoSave:
  Enable: true
  Interval: 6000
  MessageEnable: true
  StartMessage: "&7セーブしています..."
  FinishMessage: "&7セーブが完了しました。"
AutoBackup:
  Enable: true
  seichi915BackupVersion: "1.0.0"
  Interval: 144000
  Location: "/mnt/Backup/"
  MessageEnable: true
  StartMessage: "&7バックアップしています..."
  FinishMessage: "&7バックアップが完了しました。"